spring.application.name=quan_ly_con_heo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_con_heo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=codegym
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

